# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ou-social-network-commentdb
    username: root
    password: IamPhong89
    # url: jdbc:mysql://ou-social-network.mysql.database.azure.com:3306/ou-social-network-commentdb
    # username: ousocialnetwork
    # password: SVDaiHocMo2020?!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: comment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event-notification:com.ou.commentservice.event.NotificationEvent, event-comment:com.ou.commentservice.event.CommentEvent, event-reply:com.ou.commentservice.event.ReplyEvent, event-commenttotal:com.ou.commentservice.event.CommentTotalEvent

#JPA/Hibernate
server:
  error:
    include-message: always
  # port: 8083
  port: 0
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
