eureka:
    instance:
        hostname: 10.0.193.60
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://10.0.193.60:8761/eureka

server:
    port: 8761