# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
  application:
    name: admin-service

#JPA/Hibernate
server:
  error:
    include-message: always
  port: 8081
  # port: 80
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.193.60:8761/eureka
  instance:
    prefer-ip-address: true