# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
  application:
    name: realtime-service
  kafka:
    bootstrap-servers: 10.0.163.82:9092
    template:
      default-topic: realtimeTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event-post:com.ou.realtimeservice.event.PostEvent, event-userdoc:com.ou.realtimeservice.event.UserDocEvent, event-uploadavatar:com.ou.realtimeservice.event.UploadAvatarEvent, event-notification:com.ou.realtimeservice.event.NotificationEvent, event-comment:com.ou.realtimeservice.event.CommentEvent, event-reply:com.ou.realtimeservice.event.ReplyEvent, event-commenttotal:com.ou.realtimeservice.event.CommentTotalEvent, event-reaction:com.ou.realtimeservice.event.PostReactionEvent

#JPA/Hibernate
server:
  error:
    include-message: always
  #port: 8086
  port: 0  
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.24.90:8761/eureka
  instance:
    prefer-ip-address: true