spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
#Logging
logging:
  level:
    root: INFO
    web: INFO
    org:
      springframework:
        security: INFO