spring:
#   servlet:
#         multipart:
#           max-file-size: 10MB
#           max-request-size: 10MB
  main:
    allow-circular-references: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            
    
#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: TRACE