apiVersion: apps/v1
kind: Deployment
metadata:
  name: ousocialnetworkserver
spec:
  selector:
    matchLabels:
      app: ousocialnetworkserver
  replicas: 1
  template:
    metadata:
      labels:
        app: ousocialnetworkserver
    spec:
      containers:
        - name: ousocialnetworkserver
          image: phonglai0809/ou-social-network:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  host
            - name: DB_NAME
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  dbName
            - name: DB_USERNAME
              valueFrom :
                secretKeyRef :
                  name : mysql-secret
                  key :  username
            - name: DB_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secret
                  key :  password