apiVersion: v1
kind: Service
metadata:
  name: ousocialnetworkserver-service
spec:
  type: LoadBalancer
  selector:
    app: ousocialnetworkserver
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80