# ConfigurationDB
spring:
  mail:
    host: cp03hn.emailserver.net.vn
    port: 465
    username: ousocialnetwork@ousocialnetwork.id.vn
    password: Vo2Z%)nF_+,{
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            protocols: TLSv1.2
            trust: "*"
        debug: true
  application:
    name: mail-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: mailTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.ou.mailservice.pojo.OrderPlacedEvent

#JPA/Hibernate
server:
  error:
    include-message: always
  port: 8084
  # port: 80
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO

