# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/ou-social-network-accountdb
    # username: root
    # password: IamPhong89
    url: jdbc:mysql://ou-social-network.mysql.database.azure.com:3306/ou-social-network-accountdb
    username: ousocialnetwork
    password: SVDaiHocMo2020?!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: 10.0.54.147:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event-mailaccount:com.ou.accountservice.event.AccountMailEvent, event-userdoc:com.ou.accountservice.event.UserDocEvent, event-uploadavatar:com.ou.accountservice.event.UploadAvatarEvent
  application:
    name: account-service
  cache:
    type: REDIS
    redis:
      time-to-live: 60000
      cache-null-values: true
  data:
    redis:
      host: 10.0.46.36
      port: 6379

#JPA/Hibernate
server:
  error:
    include-message: always
  port: 8082

#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.193.60:8761/eureka
  instance:
    prefer-ip-address: true