# ConfigurationDB
spring:
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/ou-social-network-postdb
    # username: root
    # password: IamPhong89
    url: jdbc:mysql://ou-social-network.mysql.database.azure.com:3306/ou-social-network-postdb
    username: ousocialnetwork
    password: SVDaiHocMo2020?!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: post-service
  kafka:
    bootstrap-servers: 10.0.163.82:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event-post:com.ou.postservice.event.PostEvent, event-notification:com.ou.postservice.event.NotificationEvent, event-mailpost:com.ou.postservice.event.PostMailEvent, event-reaction:com.ou.postservice.event.PostReactionEvent

#JPA/Hibernate
server:
  error:
    include-message: always
  #port: 8085
  port: 0  
  # servlet:
  #   context-path: /social_network


#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.24.90:8761/eureka
  instance:
    prefer-ip-address: true