apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: phonglai0809/ou-social-network-eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761